"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" General
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Sets how many lines of history VIM has to remember
set history=500

" Enable filetype plugins
filetype plugin on
filetype indent on

" Set to auto read when a file is changed from the outside
set autoread

" With a map leader it's possible to do extra key combinations
" like <leader>w saves the current file
let mapleader = ","
let g:mapleader = ","

" Fast saving
nmap <leader>w :w!<cr>

set nocompatible

" Display relative line numbers
set number
set relativenumber

syntax enable

" Provides tab-completion for all file-related tasks
set path+=**

" Display all matching files when doing tab complete
set wildmenu

" Insert mode completion                         ins-completion  

" Auto-Complete spell check, when spell is on
set complete+=kspell

" Add dictionaries
set thesaurus+=$HOME/vimfiles/dict/moby-thesaurus.txt
set dictionary+=$HOME/vimfiles/dict/words.txt

" Create the 'tags' file
command! MakeTags !ctags -R .
" Look up a directory if not found
set tags+=tag;/

call plug#begin('$HOME/vimfiles/plugged')

Plug 'tpope/vim-surround'
Plug 'editorconfig/editorconfig-vim'
Plug 'scrooloose/nerdtree', { 'on' : 'NERDTreeToggle'}

call plug#end()


